[package]
name = "grub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
insta = { version = "1.30.0", features = ["yaml"] }

[dependencies]
thiserror = "1.0.40"
