# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12207ee987ce045596cb992cfb15b0d6d9456e50d4721c3061c69dabc2962053644d";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/c0193e9247335a6c1688b946325060289405de2a.tar.gz";
      hash = "sha256-7RoauPCvwLutCpP0XP6AvjDUXszDKnKyid1RoQvxFPI=";
    };
  }
]
