# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220949d4e88864579067b6d4cdad6476c6176f27e782782c2c39b7f2c4817a10efb";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.8.0.tar.gz";
      hash = "sha256-nbNJX+TelWeo6i79Ufcn1r2yKMfbpu/+OTo+Y4UATl8=";
    };
  }
]
