# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "122051750f4d7ecc9b705f1bbea1d431956306c74dafa4e9b625b11a34fab4c06933";
    path = fetchzip {
      url = "https://github.com/r4gus/zbor/archive/refs/tags/0.13.1.tar.gz";
      hash = "sha256-AMhdM20LA+NP4nJSvIPvr8N+Xk36C4WqUOc70PLYkWA=";
    };
  }
]
