[package]
name = "boot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grub = { path = "../grub" }
libc = "0.2.139"
log = "0.4.17"
