[package]
name = "tbootd"
version = "0.1.0"
edition = "2021"

[features]
default = []
measured-boot = []
verified-boot = []

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
grub = { path = "../grub" }
log = "0.4.17"
nix = "0.26.2"
sha2 = "0.10.6"
syscalls = "0.6.10"
tboot = { path = "../tboot" }
termion = "2.0.1"
uuid = "1.2.2"

[build-dependencies]
bindgen = { version = "0.65.1" }
