[package]
name = "tbootd"
version = "0.1.0"
edition = "2021"

[features]
default = []
measured-boot = []
verified-boot = []

[build-dependencies]
bindgen = { version = "0.65.1" }

[dependencies]
anyhow = "1.0.71"
bytes = "1.4.0"
clap = { version = "4.3.0", features = ["derive"] }
crc = "3.0.1"
grub = { path = "../grub" }
hex = "0.4.3"
kobject-uevent = "0.1.0"
log = "0.4.18"
netlink-sys = { version = "0.8.5" }
nix = "0.26.2"
sha2 = "0.10.6"
syscalls = "0.6.12"
tboot = { path = "../tboot" }
termion = "2.0.1"
uuid = "~1.2"
