[package]
name = "tinyboot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", default-features = false, features = [
  "std",
  "derive",
] }
fern = "0.6.1"
grub = { path = "../grub" }
log = "0.4.17"
nix = "0.26.2"
termion = "1.5.6"
tui = { version = "0.19", default-features = false, features = ["termion"] }
uuid = "1.2.2"
