[package]
name = "tinyboot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
boot = { path = "../boot" }
fern = "0.6.1"
log = "0.4.17"
nix = "0.26.1"
termion = "2.0.1"
tui = { version = "0.19", default-features = false, features = ["termion"] }
