[package]
name = "tbootctl"
version = "0.1.0"
edition = "2021"

[build-dependencies]
clap.workspace = true
clap_complete = "4.3.2"

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
log.workspace = true
tboot.workspace = true
tokio.workspace = true
