name: build
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check various builds
        run: nix build --print-build-logs .\#tinybootLoader .\#tinybootTools .\#pkgsCross.aarch64-multiplatform.tinybootLoader .\#pkgsCross.aarch64-multiplatform.tinybootTools
      - name: Check nix flake
        run: nix flake check --print-build-logs
