name: build
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Native build for x86_64-linux
        run: nix build --print-build-logs .\#tinyboot
      - name: Cross build for aarch64-linux
        run: nix build --print-build-logs .\#pkgsCross.aarch64-multiplatform.tinyboot
      - name: Check nix flake
        run: nix flake check --print-build-logs
